---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - claim.seung.com
  resources:
  - clusterclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - claim.seung.com
  resources:
  - clusterclaims/finalizers
  verbs:
  - update
- apiGroups:
  - claim.seung.com
  resources:
  - clusterclaims/status
  verbs:
  - get
  - patch
  - update
